export const API_V1 = {
  CONFIGS: '/configs',
  CONFIG_DETAIL: (id: string) => `/configs/${id}`,
  PIPELINES: '/pipelines',
  PIPELINE_DETAIL: (id: string) => `/pipelines/${id}`,
  PIPELINE_RUN: (id: string) => `/pipelines/${id}/run`,
  PIPELINE_VALIDATE: (id: string) => `/pipelines/${id}/validate`,
  TABLES: '/schema/tables',
  COLUMNS: (table: string) => `/schema/tables/${table}/columns`,
  MIGRATION_JOBS: '/jobs',
  MIGRATION_JOB_STATUS: (id: string) => `/jobs/${id}/status`,
  MIGRATION_JOB_STOP: (id: string) => `/jobs/${id}/stop`,
  DATASOURCES: '/datasources',
  DATASOURCE_DETAIL: (id: string) => `/datasources/${id}`,
  DB_EXPLORERS: '/db-explorers',
  DATASOURCE_TABLES: (id: string) => `/datasources/${id}/tables`,
  DATASOURCE_TABLE_COLUMNS: (id: string, table: string) =>
    `/datasources/${id}/tables/${table}/columns`,
  TRANSFORMERS: '/transformers',
  VALIDATORS: '/validators',
  PIPELINE_JOBS: (id: string) => `/pipelines/${id}/jobs`,
  JOB_PIPELINE_RUNS: (id: string) => `/jobs/${id}/pipeline-runs`,
  PIPELINE_DUPLICATE: (id: string) => `/pipelines/${id}/duplicate`,
  CONFIG_DUPLICATE: (id: string) => `/configs/${id}/duplicate`,
} as const;
